/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import domain.Carnivoro;
import domain.Especie;
import domain.Herbivoro;
import domain.Pais;
import domain.Sector;
import domain.TipoAlimentacion;
import java.util.InvalidPropertiesFormatException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author jeremias
 */
public class AgregarAnimalesView extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAnimales
     */
    public AgregarAnimalesView() {
        initComponents();
    }
    
    public void ejecutar(){
        
        this.setVisible(true);
        setDatos();
        
    }
    
    public void setDatos(){
        
        DefaultComboBoxModel box1 = new DefaultComboBoxModel();
        DefaultComboBoxModel box2 = new DefaultComboBoxModel();
        DefaultComboBoxModel box3 = new DefaultComboBoxModel();
        
        box1.addElement("Seleccione una especie");
        
        for(Especie esp : Controlador.getEspecies()){
            
            box1.addElement(esp.getNombre());
            
        }
        
        jComboBox1.setModel(box1);
        
        box2.addElement("Seleccione un sector");
        
        for(Sector sec : Controlador.getSectores()){
            
            box2.addElement(sec.getNumero());
            
        }
        
        jComboBox2.setModel(box2);
        
        box3.addElement("Seleccione un Pais");
        
        for(Pais pa : Controlador.getPaises()){
            
            box3.addElement(pa.getNombre());
            
        }
        
        jComboBox3.setModel(box3);
        
        this.edad.setInputVerifier(new IntegerInputVerifier());
        this.peso.setInputVerifier(new DoubleInputVerifier());
        
        jComboBox1.addActionListener(evt -> actualizarSectoresDisponibles());
        jComboBox1.addActionListener(e -> actualizarEstadoTextField());
    
    // Actualizar sectores inicialmente
        actualizarSectoresDisponibles();
        
    }
      
    private void actualizarSectoresDisponibles() {
        // Obtener especie seleccionada
        String nombreEspecie = (String) jComboBox1.getSelectedItem();
        Especie especieSeleccionada = null;
                
        // Buscar la especie por nombre
        for (Especie esp : Controlador.getEspecies()) {
            if (esp.getNombre().equals(nombreEspecie)) {
                especieSeleccionada = esp;
                break;
            }
        }

        if (especieSeleccionada != null) {
            // Filtrar sectores por tipo de alimentación
            DefaultComboBoxModel<String> modeloSectores = new DefaultComboBoxModel<>();
            TipoAlimentacion alimentacionRequerida = especieSeleccionada.getTipoAlimentacion();
            modeloSectores.addElement("Seleccione un Sector");
            for (Sector sec : Controlador.getSectores()) {
                if (sec.getTipoAlimentacion().equals(alimentacionRequerida)) {
                    String item = String.valueOf(sec.getNumero());
                    modeloSectores.addElement(item);
                }
            }

            jComboBox2.setModel(modeloSectores);
            
        }
    }
    
    private void actualizarEstadoTextField() {
        String nombreEspecieSeleccionada = (String) jComboBox1.getSelectedItem();
        Especie especie = null;
        
        for (Especie esp : Controlador.getEspecies()) {
            if (esp.getNombre().equals(nombreEspecieSeleccionada)) {
                especie = esp;
                break;
            }
        }

        if (especie != null) {
            
            this.comidaFija.setEnabled(especie.getTipoAlimentacion().esHerbivoro());
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        edad = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        agregarAnimal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comidaFija = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Sector");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agregarAnimal.setText("Agregar Animal");
        agregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAnimalActionPerformed(evt);
            }
        });

        jLabel6.setText("Pais");

        jLabel1.setText("Agregar Nuevo Animal");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Edad");

        jLabel7.setText("Cantidad de comida extra fija");

        jLabel3.setText("Peso");

        jLabel4.setText("Especie");

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comidaFija, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cerrar)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comidaFija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarAnimal)
                    .addComponent(Cerrar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAnimalActionPerformed
        // TODO add your handling code here:

        String nombreEspecie = (String) jComboBox1.getSelectedItem();
        int numeroSector = Integer.parseInt((String) jComboBox2.getSelectedItem());
        Especie especieS = null;
        Sector sector = null;
        Pais pais = null;

        // Buscar la especie por nombre
        for (Especie esp : Controlador.getEspecies()) {
            if (esp.getNombre().equals(nombreEspecie)) {
                especieS = esp;
                break;
            }
        }

        for (Sector sec : Controlador.getSectores()){
            if (sec.getNumero() == numeroSector) {
                sector = sec;
                break;
            }
        }

        for (Pais pa : Controlador.getPaises()){
            if (pa.getNombre().equals((String)this.jComboBox3.getSelectedItem())) {
                pais = pa;
                break;
            }
        }

        if(especieS.getTipoAlimentacion().esCarnivoro()){

            try {
                Controlador.agregarAnimal(null, new Carnivoro(Integer.parseInt(this.edad.getText()),Double.parseDouble(this.peso.getText()),especieS,sector,pais));
            } catch (InvalidPropertiesFormatException ex) {
                Logger.getLogger(AgregarAnimalesView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{

            try {
                Controlador.agregarAnimal(new Herbivoro(Integer.parseInt(this.edad.getText()),Double.parseDouble(this.peso.getText()),especieS,sector,Double.parseDouble(this.comidaFija.getText()),pais),null);
            } catch (InvalidPropertiesFormatException ex) {
                Logger.getLogger(AgregarAnimalesView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_agregarAnimalActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton agregarAnimal;
    private javax.swing.JTextField comidaFija;
    private javax.swing.JTextField edad;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField peso;
    // End of variables declaration//GEN-END:variables
}
